### PR TITLE
Step to allow publishing of arbitrary messages from pipeline jobs

### PR DESCRIPTION
**Pull request by GLundh**
With the introduction of pipeline support various dependencies had
to be updated.

Inlined the dependency versions in pom.xml since the defining them
in a seperate section was unnecessary and messed with IDEAs
autocompletion and validation.

Typical usage:

   publishMQMessage '{"test" : ["value", 1]}'

### CODE REVIEW

**Review by jonsten — CHANGES_REQUESTED** [review]
Over all looks good and a nice contribution. Would be nice to see a test for this, e.g.:
```
    @Test
    public void testPipelineStep() throws Exception {
        MQNotifierConfig config = MQNotifierConfig.getInstance();
        config.setEnableNotifier(true);

        String message = "{\"key\":\"value\"}";

        WorkflowJob job = j.createProject(WorkflowJob.class);
        job.setDefinition(new CpsFlowDefinition("publishMQMessage '" + message + "'", true));

        j.buildAndAssertSuccess(job);
        assertThat(Mocks.MESSAGES, Matchers.hasItem(message));
    }
```
I would also suggest the addition of the following config.groovy (com/sonymobile/jenkins/plugins/mq/mqnotifier/pipeline/MQMessageStep/config.groovy), it enables the plugin in the snippet generator:
```
package com.sonymobile.jenkins.plugins.mq.mqnotifier.pipeline.MQMessageStep

import lib.FormTagLib

def f = namespace(FormTagLib)

f.entry(field: 'json',
        title: 'JSON Message',
        description: 'JSON Message to be sent to the RabbitMQ server.') {
    f.textbox()
}
```

**Comment by GLundh** [comment]
Thanks! Since the Test and UI code for the PR is yours, I added a "Signed-off-by:"-footer on the second commit. Let me know if you would prefer to re-push it with you as the author instead.

**Comment by magnusbaeck** [comment]
It'd be useful to be able to specify the topic the message should be published to, but that's something we can add later without causing incompatibilities.

**Comment by jonsten** [comment]
@GLundh, sign off is good enough for me.

**Review by jonsten — APPROVED** [review]

**Pull request merged**
